<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ramadevi" failures="1" tests="4" name="selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials" time="33.749" errors="0" timestamp="2024-10-07T14:47:56 EDT" skipped="2">
  <testcase classname="selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials" name="login_button" time="5.003">
    <skipped/>
  </testcase> <!-- login_button -->
  <testcase classname="selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials" name="login_button" time="7.992">
    <failure message="expected [Authentication required] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Authentication required] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials.login_button(Testcase3_Amazon_login_testcase_incorrect_credentials.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
    <system-out>
      <![CDATA[My test case is failed]]>
    </system-out>
  </testcase> <!-- login_button -->
  <testcase classname="selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials" name="login_button" time="11.463">
    <skipped/>
  </testcase> <!-- login_button -->
  <testcase classname="selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials" name="login_button" time="9.291">
    <system-out>
      <![CDATA[My test case is passs]]>
    </system-out>
  </testcase> <!-- login_button -->
  <system-out>
    <![CDATA[My test case is passs
My test case is failed
My test case is passs
My test case is passs
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is passs
My test case is failed
My test case is failed
My test case is passs
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is failed
My test case is passs
My test case is failed]]>
  </system-out>
</testsuite> <!-- selenium1.selenium1.Testcase3_Amazon_login_testcase_incorrect_credentials -->
